services:
  # Catalog Database - stores tenant metadata
  catalog-postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=catalog_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5433:5432'
    volumes:
      - catalog-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d catalog_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Tenant 1 Database
  tenant1-postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=tenant_company1'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5434:5432'
    volumes:
      - tenant1-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d tenant_company1"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Tenant 2 Database
  tenant2-postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=tenant_company2'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5435:5432'
    volumes:
      - tenant2-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d tenant_company2"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: 'rabbitmq:3-management'
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: 'mas-java-poc:latest'
    build: .
    depends_on:
      catalog-postgres:
        condition: service_healthy
      tenant1-postgres:
        condition: service_healthy
      tenant2-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_CATALOG_URL: jdbc:postgresql://catalog-postgres:5432/catalog_db
      SPRING_DATASOURCE_CATALOG_USERNAME: myuser
      SPRING_DATASOURCE_CATALOG_PASSWORD: secret
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      MULTITENANCY_ENABLED: true
    ports:
      - '8080:8080'

volumes:
  catalog-data:
  tenant1-data:
  tenant2-data:
