spring:
  # Disable Docker Compose support during OpenAPI generation
  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:h2:mem:openapi-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
    catalog:
      jdbc-url: jdbc:h2:mem:catalog-db
      driver-class-name: org.h2.Driver
      username: sa
      password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: false

  security:
    user:
      name: admin
      password: admin

  # Disable RabbitMQ and Quartz auto-configuration during OpenAPI generation
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration

# Disable multi-tenancy during OpenAPI generation
multitenancy:
  enabled: false

# Disable unnecessary features during OpenAPI generation
management:
  endpoints:
    enabled-by-default: false

logging:
  level:
    root: WARN
    org.springframework: WARN
